import 'package:flutter/cupertino.dart';
import 'package:flutter_common/l10n/app_localizations.dart';

String getLocalizedCountryName(BuildContext context, String countryCode) {
  switch (countryCode) {
    case 'AF':
      return AppLocalizations.of(context)!.country_AF;
    case 'AX':
      return AppLocalizations.of(context)!.country_AX;
    case 'AL':
      return AppLocalizations.of(context)!.country_AL;
    case 'DZ':
      return AppLocalizations.of(context)!.country_DZ;
    case 'AS':
      return AppLocalizations.of(context)!.country_AS;
    case 'AD':
      return AppLocalizations.of(context)!.country_AD;
    case 'AO':
      return AppLocalizations.of(context)!.country_AO;
    case 'AI':
      return AppLocalizations.of(context)!.country_AI;
    case 'AQ':
      return AppLocalizations.of(context)!.country_AQ;
    case 'AG':
      return AppLocalizations.of(context)!.country_AG;
    case 'AR':
      return AppLocalizations.of(context)!.country_AR;
    case 'AM':
      return AppLocalizations.of(context)!.country_AM;
    case 'AW':
      return AppLocalizations.of(context)!.country_AW;
    case 'AU':
      return AppLocalizations.of(context)!.country_AU;
    case 'AT':
      return AppLocalizations.of(context)!.country_AT;
    case 'AZ':
      return AppLocalizations.of(context)!.country_AZ;
    case 'BH':
      return AppLocalizations.of(context)!.country_BH;
    case 'BD':
      return AppLocalizations.of(context)!.country_BD;
    case 'BB':
      return AppLocalizations.of(context)!.country_BB;
    case 'BY':
      return AppLocalizations.of(context)!.country_BY;
    case 'BE':
      return AppLocalizations.of(context)!.country_BE;
    case 'BZ':
      return AppLocalizations.of(context)!.country_BZ;
    case 'BJ':
      return AppLocalizations.of(context)!.country_BJ;
    case 'BM':
      return AppLocalizations.of(context)!.country_BM;
    case 'BT':
      return AppLocalizations.of(context)!.country_BT;
    case 'BO':
      return AppLocalizations.of(context)!.country_BO;
    case 'BQ':
      return AppLocalizations.of(context)!.country_BQ;
    case 'BA':
      return AppLocalizations.of(context)!.country_BA;
    case 'BW':
      return AppLocalizations.of(context)!.country_BW;
    case 'BV':
      return AppLocalizations.of(context)!.country_BV;
    case 'BR':
      return AppLocalizations.of(context)!.country_BR;
    case 'IO':
      return AppLocalizations.of(context)!.country_IO;
    case 'BN':
      return AppLocalizations.of(context)!.country_BN;
    case 'BG':
      return AppLocalizations.of(context)!.country_BG;
    case 'BF':
      return AppLocalizations.of(context)!.country_BF;
    case 'BI':
      return AppLocalizations.of(context)!.country_BI;
    case 'KH':
      return AppLocalizations.of(context)!.country_KH;
    case 'CM':
      return AppLocalizations.of(context)!.country_CM;
    case 'CA':
      return AppLocalizations.of(context)!.country_CA;
    case 'CV':
      return AppLocalizations.of(context)!.country_CV;
    case 'KY':
      return AppLocalizations.of(context)!.country_KY;
    case 'CF':
      return AppLocalizations.of(context)!.country_CF;
    case 'TD':
      return AppLocalizations.of(context)!.country_TD;
    case 'CL':
      return AppLocalizations.of(context)!.country_CL;
    case 'CX':
      return AppLocalizations.of(context)!.country_CX;
    case 'CC':
      return AppLocalizations.of(context)!.country_CC;
    case 'CO':
      return AppLocalizations.of(context)!.country_CO;
    case 'KM':
      return AppLocalizations.of(context)!.country_KM;
    case 'CG':
      return AppLocalizations.of(context)!.country_CG;
    case 'CK':
      return AppLocalizations.of(context)!.country_CK;
    case 'CR':
      return AppLocalizations.of(context)!.country_CR;
    case 'CI':
      return AppLocalizations.of(context)!.country_CI;
    case 'HR':
      return AppLocalizations.of(context)!.country_HR;
    case 'CU':
      return AppLocalizations.of(context)!.country_CU;
    case 'CW':
      return AppLocalizations.of(context)!.country_CW;
    case 'CY':
      return AppLocalizations.of(context)!.country_CY;
    case 'CZ':
      return AppLocalizations.of(context)!.country_CZ;
    case 'CD':
      return AppLocalizations.of(context)!.country_CD;
    case 'DK':
      return AppLocalizations.of(context)!.country_DK;
    case 'DJ':
      return AppLocalizations.of(context)!.country_DJ;
    case 'DM':
      return AppLocalizations.of(context)!.country_DM;
    case 'DO':
      return AppLocalizations.of(context)!.country_DO;
    case 'EC':
      return AppLocalizations.of(context)!.country_EC;
    case 'EG':
      return AppLocalizations.of(context)!.country_EG;
    case 'SV':
      return AppLocalizations.of(context)!.country_SV;
    case 'GQ':
      return AppLocalizations.of(context)!.country_GQ;
    case 'ER':
      return AppLocalizations.of(context)!.country_ER;
    case 'EE':
      return AppLocalizations.of(context)!.country_EE;
    case 'SZ':
      return AppLocalizations.of(context)!.country_SZ;
    case 'ET':
      return AppLocalizations.of(context)!.country_ET;
    case 'FK':
      return AppLocalizations.of(context)!.country_FK;
    case 'FO':
      return AppLocalizations.of(context)!.country_FO;
    case 'FJ':
      return AppLocalizations.of(context)!.country_FJ;
    case 'FI':
      return AppLocalizations.of(context)!.country_FI;
    case 'FR':
      return AppLocalizations.of(context)!.country_FR;
    case 'GF':
      return AppLocalizations.of(context)!.country_GF;
    case 'PF':
      return AppLocalizations.of(context)!.country_PF;
    case 'TF':
      return AppLocalizations.of(context)!.country_TF;
    case 'GA':
      return AppLocalizations.of(context)!.country_GA;
    case 'GE':
      return AppLocalizations.of(context)!.country_GE;
    case 'DE':
      return AppLocalizations.of(context)!.country_DE;
    case 'GH':
      return AppLocalizations.of(context)!.country_GH;
    case 'GI':
      return AppLocalizations.of(context)!.country_GI;
    case 'GR':
      return AppLocalizations.of(context)!.country_GR;
    case 'GL':
      return AppLocalizations.of(context)!.country_GL;
    case 'GD':
      return AppLocalizations.of(context)!.country_GD;
    case 'GP':
      return AppLocalizations.of(context)!.country_GP;
    case 'GU':
      return AppLocalizations.of(context)!.country_GU;
    case 'GT':
      return AppLocalizations.of(context)!.country_GT;
    case 'GG':
      return AppLocalizations.of(context)!.country_GG;
    case 'GN':
      return AppLocalizations.of(context)!.country_GN;
    case 'GW':
      return AppLocalizations.of(context)!.country_GW;
    case 'GY':
      return AppLocalizations.of(context)!.country_GY;
    case 'HT':
      return AppLocalizations.of(context)!.country_HT;
    case 'HM':
      return AppLocalizations.of(context)!.country_HM;
    case 'HN':
      return AppLocalizations.of(context)!.country_HN;
    case 'HK':
      return AppLocalizations.of(context)!.country_HK;
    case 'HU':
      return AppLocalizations.of(context)!.country_HU;
    case 'IS':
      return AppLocalizations.of(context)!.country_IS;
    case 'IN':
      return AppLocalizations.of(context)!.country_IN;
    case 'ID':
      return AppLocalizations.of(context)!.country_ID;
    case 'IR':
      return AppLocalizations.of(context)!.country_IR;
    case 'IQ':
      return AppLocalizations.of(context)!.country_IQ;
    case 'IE':
      return AppLocalizations.of(context)!.country_IE;
    case 'IL':
      return AppLocalizations.of(context)!.country_IL;
    case 'IT':
      return AppLocalizations.of(context)!.country_IT;
    case 'JM':
      return AppLocalizations.of(context)!.country_JM;
    case 'JP':
      return AppLocalizations.of(context)!.country_JP;
    case 'JE':
      return AppLocalizations.of(context)!.country_JE;
    case 'JO':
      return AppLocalizations.of(context)!.country_JO;
    case 'KZ':
      return AppLocalizations.of(context)!.country_KZ;
    case 'KE':
      return AppLocalizations.of(context)!.country_KE;
    case 'KI':
      return AppLocalizations.of(context)!.country_KI;
    case 'XK':
      return AppLocalizations.of(context)!.country_XK;
    case 'KW':
      return AppLocalizations.of(context)!.country_KW;
    case 'KG':
      return AppLocalizations.of(context)!.country_KG;
    case 'LA':
      return AppLocalizations.of(context)!.country_LA;
    case 'LV':
      return AppLocalizations.of(context)!.country_LV;
    case 'LB':
      return AppLocalizations.of(context)!.country_LB;
    case 'LS':
      return AppLocalizations.of(context)!.country_LS;
    case 'LR':
      return AppLocalizations.of(context)!.country_LR;
    case 'LY':
      return AppLocalizations.of(context)!.country_LY;
    case 'LI':
      return AppLocalizations.of(context)!.country_LI;
    case 'LT':
      return AppLocalizations.of(context)!.country_LT;
    case 'LU':
      return AppLocalizations.of(context)!.country_LU;
    case 'MO':
      return AppLocalizations.of(context)!.country_MO;
    case 'MG':
      return AppLocalizations.of(context)!.country_MG;
    case 'MW':
      return AppLocalizations.of(context)!.country_MW;
    case 'MY':
      return AppLocalizations.of(context)!.country_MY;
    case 'MV':
      return AppLocalizations.of(context)!.country_MV;
    case 'ML':
      return AppLocalizations.of(context)!.country_ML;
    case 'MT':
      return AppLocalizations.of(context)!.country_MT;
    case 'IM':
      return AppLocalizations.of(context)!.country_IM;
    case 'MH':
      return AppLocalizations.of(context)!.country_MH;
    case 'MQ':
      return AppLocalizations.of(context)!.country_MQ;
    case 'MR':
      return AppLocalizations.of(context)!.country_MR;
    case 'MU':
      return AppLocalizations.of(context)!.country_MU;
    case 'YT':
      return AppLocalizations.of(context)!.country_YT;
    case 'MX':
      return AppLocalizations.of(context)!.country_MX;
    case 'FM':
      return AppLocalizations.of(context)!.country_FM;
    case 'MD':
      return AppLocalizations.of(context)!.country_MD;
    case 'MC':
      return AppLocalizations.of(context)!.country_MC;
    case 'MN':
      return AppLocalizations.of(context)!.country_MN;
    case 'ME':
      return AppLocalizations.of(context)!.country_ME;
    case 'MS':
      return AppLocalizations.of(context)!.country_MS;
    case 'MA':
      return AppLocalizations.of(context)!.country_MA;
    case 'MZ':
      return AppLocalizations.of(context)!.country_MZ;
    case 'MM':
      return AppLocalizations.of(context)!.country_MM;
    case 'NA':
      return AppLocalizations.of(context)!.country_NA;
    case 'NR':
      return AppLocalizations.of(context)!.country_NR;
    case 'NP':
      return AppLocalizations.of(context)!.country_NP;
    case 'NL':
      return AppLocalizations.of(context)!.country_NL;
    case 'NC':
      return AppLocalizations.of(context)!.country_NC;
    case 'NZ':
      return AppLocalizations.of(context)!.country_NZ;
    case 'NI':
      return AppLocalizations.of(context)!.country_NI;
    case 'NE':
      return AppLocalizations.of(context)!.country_NE;
    case 'NG':
      return AppLocalizations.of(context)!.country_NG;
    case 'NU':
      return AppLocalizations.of(context)!.country_NU;
    case 'NF':
      return AppLocalizations.of(context)!.country_NF;
    case 'KP':
      return AppLocalizations.of(context)!.country_KP;
    case 'MK':
      return AppLocalizations.of(context)!.country_MK;
    case 'MP':
      return AppLocalizations.of(context)!.country_MP;
    case 'NO':
      return AppLocalizations.of(context)!.country_NO;
    case 'OM':
      return AppLocalizations.of(context)!.country_OM;
    case 'PK':
      return AppLocalizations.of(context)!.country_PK;
    case 'PW':
      return AppLocalizations.of(context)!.country_PW;
    case 'PS':
      return AppLocalizations.of(context)!.country_PS;
    case 'PA':
      return AppLocalizations.of(context)!.country_PA;
    case 'PG':
      return AppLocalizations.of(context)!.country_PG;
    case 'PY':
      return AppLocalizations.of(context)!.country_PY;
    case 'PE':
      return AppLocalizations.of(context)!.country_PE;
    case 'PH':
      return AppLocalizations.of(context)!.country_PH;
    case 'PN':
      return AppLocalizations.of(context)!.country_PN;
    case 'PL':
      return AppLocalizations.of(context)!.country_PL;
    case 'PT':
      return AppLocalizations.of(context)!.country_PT;
    case 'PR':
      return AppLocalizations.of(context)!.country_PR;
    case 'QA':
      return AppLocalizations.of(context)!.country_QA;
    case 'RE':
      return AppLocalizations.of(context)!.country_RE;
    case 'RO':
      return AppLocalizations.of(context)!.country_RO;
    case 'RU':
      return AppLocalizations.of(context)!.country_RU;
    case 'RW':
      return AppLocalizations.of(context)!.country_RW;
    case 'SH':
      return AppLocalizations.of(context)!.country_SH;
    case 'KN':
      return AppLocalizations.of(context)!.country_KN;
    case 'LC':
      return AppLocalizations.of(context)!.country_LC;
    case 'PM':
      return AppLocalizations.of(context)!.country_PM;
    case 'VC':
      return AppLocalizations.of(context)!.country_VC;
    case 'BL':
      return AppLocalizations.of(context)!.country_BL;
    case 'MF':
      return AppLocalizations.of(context)!.country_MF;
    case 'WS':
      return AppLocalizations.of(context)!.country_WS;
    case 'SM':
      return AppLocalizations.of(context)!.country_SM;
    case 'ST':
      return AppLocalizations.of(context)!.country_ST;
    case 'SA':
      return AppLocalizations.of(context)!.country_SA;
    case 'SN':
      return AppLocalizations.of(context)!.country_SN;
    case 'RS':
      return AppLocalizations.of(context)!.country_RS;
    case 'SC':
      return AppLocalizations.of(context)!.country_SC;
    case 'SL':
      return AppLocalizations.of(context)!.country_SL;
    case 'SG':
      return AppLocalizations.of(context)!.country_SG;
    case 'SX':
      return AppLocalizations.of(context)!.country_SX;
    case 'SK':
      return AppLocalizations.of(context)!.country_SK;
    case 'SI':
      return AppLocalizations.of(context)!.country_SI;
    case 'SB':
      return AppLocalizations.of(context)!.country_SB;
    case 'SO':
      return AppLocalizations.of(context)!.country_SO;
    case 'ZA':
      return AppLocalizations.of(context)!.country_ZA;
    case 'GS':
      return AppLocalizations.of(context)!.country_GS;
    case 'KR':
      return AppLocalizations.of(context)!.country_KR;
    case 'SS':
      return AppLocalizations.of(context)!.country_SS;
    case 'ES':
      return AppLocalizations.of(context)!.country_ES;
    case 'LK':
      return AppLocalizations.of(context)!.country_LK;
    case 'SD':
      return AppLocalizations.of(context)!.country_SD;
    case 'SR':
      return AppLocalizations.of(context)!.country_SR;
    case 'SJ':
      return AppLocalizations.of(context)!.country_SJ;
    case 'SE':
      return AppLocalizations.of(context)!.country_SE;
    case 'CH':
      return AppLocalizations.of(context)!.country_CH;
    case 'SY':
      return AppLocalizations.of(context)!.country_SY;
    case 'TW':
      return AppLocalizations.of(context)!.country_TW;
    case 'TJ':
      return AppLocalizations.of(context)!.country_TJ;
    case 'TZ':
      return AppLocalizations.of(context)!.country_TZ;
    case 'TH':
      return AppLocalizations.of(context)!.country_TH;
    case 'BS':
      return AppLocalizations.of(context)!.country_BS;
    case 'GM':
      return AppLocalizations.of(context)!.country_GM;
    case 'TL':
      return AppLocalizations.of(context)!.country_TL;
    case 'TG':
      return AppLocalizations.of(context)!.country_TG;
    case 'TK':
      return AppLocalizations.of(context)!.country_TK;
    case 'TO':
      return AppLocalizations.of(context)!.country_TO;
    case 'TT':
      return AppLocalizations.of(context)!.country_TT;
    case 'TN':
      return AppLocalizations.of(context)!.country_TN;
    case 'TR':
      return AppLocalizations.of(context)!.country_TR;
    case 'TM':
      return AppLocalizations.of(context)!.country_TM;
    case 'TC':
      return AppLocalizations.of(context)!.country_TC;
    case 'TV':
      return AppLocalizations.of(context)!.country_TV;
    case 'UG':
      return AppLocalizations.of(context)!.country_UG;
    case 'UA':
      return AppLocalizations.of(context)!.country_UA;
    case 'AE':
      return AppLocalizations.of(context)!.country_AE;
    case 'GB':
      return AppLocalizations.of(context)!.country_GB;
    case 'US':
      return AppLocalizations.of(context)!.country_US;
    case 'UM':
      return AppLocalizations.of(context)!.country_UM;
    case 'UY':
      return AppLocalizations.of(context)!.country_UY;
    case 'UZ':
      return AppLocalizations.of(context)!.country_UZ;
    case 'VU':
      return AppLocalizations.of(context)!.country_VU;
    case 'VA':
      return AppLocalizations.of(context)!.country_VA;
    case 'VE':
      return AppLocalizations.of(context)!.country_VE;
    case 'VN':
      return AppLocalizations.of(context)!.country_VN;
    case 'VG':
      return AppLocalizations.of(context)!.country_VG;
    case 'VI':
      return AppLocalizations.of(context)!.country_VI;
    case 'WF':
      return AppLocalizations.of(context)!.country_WF;
    case 'EH':
      return AppLocalizations.of(context)!.country_EH;
    case 'YE':
      return AppLocalizations.of(context)!.country_YE;
    case 'ZM':
      return AppLocalizations.of(context)!.country_ZM;
    case 'ZW':
      return AppLocalizations.of(context)!.country_ZW;
    default:
      return countryCode;
  }
}
